export const posts = [
  {
    id: 'post-1',
    category: 'UI Design',
    title: 'Job Post 1',
    company: 'Company Name',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit et dolore magna aliqua.',
  },
  { 
    id: 'post-2',
    category: 'Front End Development',
    title: 'Job Post 2',
    company: 'Company Name',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit et dolore magna aliqua.',
  },
  {
    id: 'post-3',
    category: 'Full Stack Development',
    title: 'Job Post 3',
    company: 'Company Name',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit et dolore magna aliqua.',
  },
  { 
    id: 'post-4',
    category: 'Copywriting',
    title: 'Job Post 4',
    company: 'Company Name',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit et dolore magna aliqua.',
  },
  {
    id: 'post-5',
    category: 'UI Design',
    title: 'Job Post 5',
    company: 'Company Name',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit et dolore magna aliqua.',
  },
  {
    id: 'post-6',
    category: 'Copywriting',
    title: 'Job Post 6',
    company: 'Company Name',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit et dolore magna aliqua.',
  },
  {
    id: 'post-7',
    category: 'Front End Development',
    title: 'Job Post 7',
    company: 'Company Name',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit et dolore magna aliqua.',
  },
  {
    id: 'post-8',
    category: 'Full Stack Development',
    title: 'Job Post 8',
    company: 'Company Name',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit et dolore magna aliqua.',
  },
  {
    id: 'post-9',
    category: 'UI Design',
    title: 'Job Post 9',
    company: 'Company Name',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit et dolore magna aliqua.',
  },
  {
    id: 'post-10',
    category: 'Front End Development',
    title: 'Job Post 10',
    company: 'Company Name',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit et dolore magna aliqua.',
  },
  {
    id: 'post-11',
    category: 'Front End Development',
    title: 'Job Post 11',
    company: 'Company Name',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit et dolore magna aliqua.',
  },
  {
    id: 'post-12',
    category: 'UI Design',
    title: 'Job Post 12',
    company: 'Company Name',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit et dolore magna aliqua.',
  },
  {
    id: 'post-13',
    category: 'Copywriting',
    title: 'Job Post 13',
    company: 'Company Name',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit et dolore magna aliqua.',
  },
  {
    id: 'post-14',
    category: 'Full Stack Development',
    title: 'Job Post 14',
    company: 'Company Name',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit et dolore magna aliqua.',
  },
  {
    id: 'post-15',
    category: 'Front End Development',
    title: 'Job Post 15',
    company: 'Company Name',
    desc: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit et dolore magna aliqua.',
  },
]

export default posts;