export const posts = [
  {    
    category: 'UI Design',
    title: 'Job Post 1',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    highlight1: '10+ Years Experience',
    highlight2: 'Salary: 70-80k',
    highlight3: 'Health Insurance',
    highlight4: 'Unlimited PTO',
    highlight5: '401k',
  },
  {     
    category: 'Front End Development',
    title: 'Job Post 2',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    highlight1: '10+ Years Experience',
    highlight2: 'Salary: 70-80k',
    highlight3: 'Health Insurance',
    highlight4: 'Unlimited PTO',
    highlight5: '401k',
  },
  {    
    category: 'Full Stack Development',
    title: 'Job Post 3',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    highlight1: '10+ Years Experience',
    highlight2: 'Salary: 70-80k',
    highlight3: 'Health Insurance',
    highlight4: 'Unlimited PTO',
    highlight5: '401k',
  },
  {     
    category: 'Copywriting',
    title: 'Job Post 4',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    highlight1: '10+ Years Experience',
    highlight2: 'Salary: 70-80k',
    highlight3: 'Health Insurance',
    highlight4: 'Unlimited PTO',
    highlight5: '401k',
  },
  {    
    category: 'UI Design',
    title: 'Job Post 5',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    highlight1: '10+ Years Experience',
    highlight2: 'Salary: 70-80k',
    highlight3: 'Health Insurance',
    highlight4: 'Unlimited PTO',
    highlight5: '401k',
  },
  {    
    category: 'Copywriting',
    title: 'Job Post 6',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    highlight1: '10+ Years Experience',
    highlight2: 'Salary: 70-80k',
    highlight3: 'Health Insurance',
    highlight4: 'Unlimited PTO',
    highlight5: '401k',
  },
  {    category: 'Front End Development',
    title: 'Job Post 7',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    highlight1: '10+ Years Experience',
    highlight2: 'Salary: 70-80k',
    highlight3: 'Health Insurance',
    highlight4: 'Unlimited PTO',
    highlight5: '401k',
  },
  {    
    category: 'Full Stack Development',
    title: 'Job Post 8',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    highlight1: '10+ Years Experience',
    highlight2: 'Salary: 70-80k',
    highlight3: 'Health Insurance',
    highlight4: 'Unlimited PTO',
    highlight5: '401k',
  },
  {    
    category: 'UI Design',
    title: 'Job Post 9',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    highlight1: '10+ Years Experience',
    highlight2: 'Salary: 70-80k',
    highlight3: 'Health Insurance',
    highlight4: 'Unlimited PTO',
    highlight5: '401k',
  },
  {
    category: 'Front End Development',
    title: 'Job Post 10',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    highlight1: '10+ Years Experience',
    highlight2: 'Salary: 70-80k',
    highlight3: 'Health Insurance',
    highlight4: 'Unlimited PTO',
    highlight5: '401k',
  },
  {
    category: 'Front End Development',
    title: 'Job Post 11',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    highlight1: '10+ Years Experience',
    highlight2: 'Salary: 70-80k',
    highlight3: 'Health Insurance',
    highlight4: 'Unlimited PTO',
    highlight5: '401k',
  },
  {
    category: 'UI Design',
    title: 'Job Post 12',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    highlight1: '10+ Years Experience',
    highlight2: 'Salary: 70-80k',
    highlight3: 'Health Insurance',
    highlight4: 'Unlimited PTO',
    highlight5: '401k',
  },
  {
    category: 'Copywriting',
    title: 'Job Post 13',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    highlight1: '10+ Years Experience',
    highlight2: 'Salary: 70-80k',
    highlight3: 'Health Insurance',
    highlight4: 'Unlimited PTO',
    highlight5: '401k',
  },
  {
    category: 'Full Stack Development',
    title: 'Job Post 14',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    highlight1: '10+ Years Experience',
    highlight2: 'Salary: 70-80k',
    highlight3: 'Health Insurance',
    highlight4: 'Unlimited PTO',
    highlight5: '401k',
  },
  {
    category: 'Front End Development',
    title: 'Job Post 15',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    highlight1: '10+ Years Experience',
    highlight2: 'Salary: 70-80k',
    highlight3: 'Health Insurance',
    highlight4: 'Unlimited PTO',
    highlight5: '401k',
  },
]

export default posts;