export const posts = [
  {    
    category: 'UI Design',
    title: 'UI Designer',
    company: 'Facebook',
    desc: 'A brief introduction and description of the post.',
    experience: '10+ Years Experience',
    salary: 'Salary: 70-80k',
    health: '100% Healthcare Coverage',
    vacation: 'Unlimited PTO',
    retirement: '401k Match',
  },
  {     
    category: 'Front End Development',
    title: 'Front End Developer',
    company: 'Google',
    desc: 'A brief introduction and description of the post.',
    experience: '10+ Years Experience',
    salary: 'Salary: 70-80k',
    health: '100% Healthcare Coverage',
    vacation: 'Unlimited PTO',
    retirement: '401k Match',
  },
  {    
    category: 'Full Stack Development',
    title: 'Full Stack Developer',
    company: 'Amazon',
    desc: 'A brief introduction and description of the post.',
    experience: '10+ Years Experience',
    salary: 'Salary: 70-80k',
    health: '100% Healthcare Coverage',
    vacation: 'Unlimited PTO',
    retirement: '401k Match',
  },
  {     
    category: 'Copywriting',
    title: 'Copywriter',
    company: 'Ogilvy & Mather',
    desc: 'A brief introduction and description of the post.',
    experience: '10+ Years Experience',
    salary: 'Salary: 70-80k',
    health: '100% Healthcare Coverage',
    vacation: 'Unlimited PTO',
    retirement: '401k Match',
  },
  {    
    category: 'UI Design',
    title: 'Job Post 5',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    experience: '10+ Years Experience',
    salary: 'Salary: 70-80k',
    health: '100% Healthcare Coverage',
    vacation: 'Unlimited PTO',
    retirement: '401k Match',
  },
  {    
    category: 'Copywriting',
    title: 'Job Post 6',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    experience: '10+ Years Experience',
    salary: 'Salary: 70-80k',
    health: '100% Healthcare Coverage',
    vacation: 'Unlimited PTO',
    retirement: '401k Match',
  },
  {    category: 'Front End Development',
    title: 'Job Post 7',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    experience: '10+ Years Experience',
    salary: 'Salary: 70-80k',
    health: '100% Healthcare Coverage',
    vacation: 'Unlimited PTO',
    retirement: '401k Match',
  },
  {    
    category: 'Full Stack Development',
    title: 'Job Post 8',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    experience: '10+ Years Experience',
    salary: 'Salary: 70-80k',
    health: '100% Healthcare Coverage',
    vacation: 'Unlimited PTO',
    retirement: '401k Match',
  },
  {    
    category: 'UI Design',
    title: 'Job Post 9',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    experience: '10+ Years Experience',
    salary: 'Salary: 70-80k',
    health: '100% Healthcare Coverage',
    vacation: 'Unlimited PTO',
    retirement: '401k Match',
  },
  {
    category: 'Front End Development',
    title: 'Job Post 10',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    experience: '10+ Years Experience',
    salary: 'Salary: 70-80k',
    health: '100% Healthcare Coverage',
    vacation: 'Unlimited PTO',
    retirement: '401k Match',
  },
  {
    category: 'Front End Development',
    title: 'Job Post 11',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    experience: '10+ Years Experience',
    salary: 'Salary: 70-80k',
    health: '100% Healthcare Coverage',
    vacation: 'Unlimited PTO',
    retirement: '401k Match',
  },
  {
    category: 'UI Design',
    title: 'Job Post 12',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    experience: '10+ Years Experience',
    salary: 'Salary: 70-80k',
    health: '100% Healthcare Coverage',
    vacation: 'Unlimited PTO',
    retirement: '401k Match',
  },
  {
    category: 'Copywriting',
    title: 'Job Post 13',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    experience: '10+ Years Experience',
    salary: 'Salary: 70-80k',
    health: '100% Healthcare Coverage',
    vacation: 'Unlimited PTO',
    retirement: '401k Match',
  },
  {
    category: 'Full Stack Development',
    title: 'Job Post 14',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    experience: '10+ Years Experience',
    salary: 'Salary: 70-80k',
    health: '100% Healthcare Coverage',
    vacation: 'Unlimited PTO',
    retirement: '401k Match',
  },
  {
    category: 'Front End Development',
    title: 'Job Post 15',
    company: 'Company Name',
    desc: 'A brief introduction and description of the post.',
    experience: '10+ Years Experience',
    salary: 'Salary: 70-80k',
    health: '100% Healthcare Coverage',
    vacation: 'Unlimited PTO',
    retirement: '401k Match',
  },
]

export default posts;